# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3040288073d35873a64397f551c4ed0db79cff98b4315e11c2dd7e9151896508735fa3504518618a7f01d6e146e835f93dc495b855f1f84fb0a7e0407c7d5d79

test:
  secret_key_base: 329094e2afd12d0809d488330dbf57a66736e9e77ad5ec322f30bf2102a463c69100ef77e29b381045b6e0c478963e634333fb6ed36a808338ce94c6bfaacdbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
